version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: nodelith-database
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-admin}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-database}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
      MYSQL_USER: ${MYSQL_USER:-admin}
    ports:
      - "3306:3306"
    volumes:
      - ./.volumes/mysql:/var/lib/mysql