name: Pull Request

on:
  pull_request:

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/.run-setup.yaml

  build:
    name: Build
    needs: setup
    uses: ./.github/workflows/.run-build.yaml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/.run-test.yaml